// Code generated by confgen. DO NOT EDIT.
// This is a default (empty) baked config for regular builds.
// Run: go run ./tools/confgen -config config/revsocks.yaml -out internal/agent/baked.go
// to generate a baked config for stealth builds.

package agent

// BakedConfig содержит захардкоженные настройки агента
type BakedConfig struct {
	Password             string
	YamuxKeepalive       int
	YamuxTimeout         int
	YamuxEnableKeepalive bool
	Servers              []string
	RetryCount           int
	RetryInterval        int
	FullCyclePause       int
	TLSEnabled           bool
	UseWebsocket         bool   // WSS режим
	Verify               bool   // Проверка TLS сертификата
	QuietMode            bool
	SocksAuthEnabled     bool
	SocksAuthUser        string
	SocksAuthPass        string
}

// DefaultBakedConfig возвращает пустую конфигурацию
func DefaultBakedConfig() *BakedConfig {
	return &BakedConfig{
		Password:             "",
		YamuxKeepalive:       30,
		YamuxTimeout:         10,
		YamuxEnableKeepalive: true,
		Servers:              nil,
		RetryCount:           3,
		RetryInterval:        30,
		FullCyclePause:       7200,
		TLSEnabled:           false,
		UseWebsocket:         false,
		Verify:               false,
		QuietMode:            false,
		SocksAuthEnabled:     false,
		SocksAuthUser:        "",
		SocksAuthPass:        "",
	}
}

// GetBakedConfig возвращает nil для обычной сборки (без baked конфига)
func GetBakedConfig() *BakedConfig {
	return nil
}

// IsBaked возвращает false для обычной сборки
func IsBaked() bool {
	return false
}
